- _config.yml
- _data/navigation.yml
- _includes/footer/custom.html
- _pages/category-archive.md
- Changes "previous elections" link language to "archive", because the resulting page also contains the current election.
> [WIP] Additional custom theming, configuration work

- _data/navigation.yml
- _layouts/home.html
Changes "Election day is..." to "The last election was..." pending the next election.
> Copy change on homepage for 'current election'

- _layouts/home.html
Adds information about 2019 election dates to the homepage.
> Adds information about 2019 election dates to the homepage

- vote.html
Updates the election date on the how to vote in Maine page.
> Updates date

- _includes/yes-no-table.html
Slightly boosts font size for yes/no table.
> Slightly increases yes/no font size for legibility

- _posts/2019-11-05-Q1_AltSignature.md
Fixes incorrect wording for "no means".
> Fixes wording for No means

- _pages/local.md
Attempts to fix the duplicate header on local elections page
> Fixes title

- _pages/local.md
Use this branch for adding links to town websites
> [WIP] Branch for adding links to town websites

- _includes/head/custom.html
Added OpenGraph(FB and others) and Twitter specific meta tags for social media sharing. Used the generic PNG logo for now, but we can always dress it up more later
#49
> Update custom.html - meta tags for OpenGraph and twitter cards

- _data/local.csv
- _pages/local.md
- contributors.html
Updates links for York County and adds new contributors to Contributors page.
> Updates York County links and contributors page

- _includes/head/custom.html
- _includes/tag-manager-body.html
- _layouts/default.html
Added plumbing for GTM to track outbound url click events in analytics
addresses #54
> Google Tag Manager Add

- _data/local.csv
Fixes #36 
Updates links for Oxford County towns.
> Updates Oxford county

- _data/local.csv
Adds a link to the campaign finance site for the Portland mayoral race.
> Adds link to campaign finance site

- _data/local.csv
> Updates Hancock County

- _data/local.csv
Adds links for Aroostook, Somerset, Franklin, Waldo, Washington, and Piscataquis counties.
> Adds remaining local election websites

- _posts/2019-11-05-Q1_Transportation.md
- _posts/2019-11-05-Q2_AltSignature.md
Adds results indicating the two statewide questions passed.
> Adds election results

- .gitignore
Adds autogenerated cache file to `.gitignore`
> Adds jekyll cache to gitignore

- _layouts/home.html
Adds text for the one local election item we know about - State House Rep for Brewer.
> Adds text about the brewer rep election.

- _posts/2020-03-03-Q1_Vaccination.md
> Fixes broken link

- _includes/election-day.html
- _posts/2020-03-03-Q1_Vaccination.md
Changes election date heading to past tense.
> Change election date to past tense

- _data/elections.yml
- _layouts/home.html
Updates election date and adds voting by mail and registering to vote by mail instructions to the homepage.
> Updates election date to July.

- _includes/candidates-data.html
- _layouts/home.html
- _pages/candidates.md
- contributors.html
- Fixes heading levels on candidates page
- Updates contributors page
- Indicates pdf in links on homepage
- Fixes header text on homepage
> Fixes text issues

- _includes/election-day.html
- _layouts/home.html
- _posts/2020-07-14-Q1_Internet.md
- _posts/2020-07-14-Q2_Transportation.md
- Updates homepage and ballot status following July election.
> Update post-July election content

- vote.html
This is an enhancement or feature.
Add the following:
Additional Resources heading 2
How to Vote in Maine embedded video with title attribute for screen reader accessibility 
Link to transcript for accessibility
Link to entire How to Vote In Every State video series
Per discussion in our meeting on Aug 20th 2020
> Add additional resources section

- package-lock.json
- package.json
This is a bug fix.
Dependabot security updates. Updates minimist and braces packages to current versions.
158
> Dependabot security updates [issue 138]

- _includes/home-info.html
Fixes case sensitivity issue on homepage
> case sensitivity fix

- _data/local_elections/local.csv
Updates local election content for York, Penobscot, Knox, Aroostook, and Franklin counties and all towns with election pages on their websites.
> Updates local election content

- _data/local_elections/local.csv
Adds local election and drop box info for remaining towns.
> Local round3

- _data/local_elections/67B4BE40
- _layouts/home.html
- _pages/local.md
Adds drop box locations for a few towns and adds copy to the homepage and local elections page about drop boxes.
> Adds drop box locations

- _includes/home-info.html
- vote.html
Adds link to state's new ballot status tool to homepage and how to vote page.
> Adds link to absentee ballot status tool

- _data/local_elections/local.csv
Adds municipal ballot information (description, link to sample) for Westbrook, per Issue #159.
> Adds Westbrook sample ballot description and link

- Gemfile.lock
- _sass/minimal-mistakes/_base.scss
- about.html
- assets/css/main.scss
- bonds.html
- vote.html
- Restores top margin to multiple page titles
> Restores top margins to page titles

- _data/local_elections/local.csv
I went through the ones to check back later and found sample ballot links and drop box locations for a few towns.
> Adds sample ballots and drop box locations for several towns

- _includes/home-info.html
Recases "Vote" to "vote" on homepage.
> Minor recasing on homepage link text

- _includes/local-election-data.html
Fixes #182
- Introduces check for archive paths to fix broken links.
> Relative path check for archive ballots

- _includes/election-day.html
Updates tense for current election
> Updates tense for election include

- _data/local_elections/local.csv
- contributors.html
Updates June election info for York, Washington, and Waldo counties.
> Updates local election info for York, Washington, and Waldo counties

- _data/local_elections/local.csv
Fixes #194, #205, #195, #199, #203, #200, #196, #197
> Adds Cumberland, Sagadahoc, Androscoggin, Kennebec, Penobscot, Knox, Aroostook, Franklin Counties

- _includes/election-day.html
- _posts/2021-11-02-Q1_ElectricTransmissionLine.md
- _posts/2021-11-02-Q2_Transportation.md
- _posts/2021-11-02-Q3_RightToFood.md
- Removes ballot type, updates tense of election date, and updates ballot question results
> Update ballot status and election tense

- _data/local_elections/local.csv
Fixes #255, #256, #257, #265, #269, #259, #260 - Adds local election content for Adroscoggin, Aroostook, Franklin, Sagadahoc, York, Knox, and Kennebec counties.
[Preview](https://deploy-preview-277--awesome-lamarr-6d076d.netlify.app/)
Thank you @inomyabcs for doing these!
> Updates local elections content

- _data/local_elections/local.csv
Adds content for remaining towns.
[Preview](https://deploy-preview-278--awesome-lamarr-6d076d.netlify.app/)
Fixes #267, #263, #264, #262, #268, #261, #266, #258
> Adds remaining local election content

- _data/local_elections/local.csv
Updates local elections content for municipalities that had content last November.
[Preview](https://deploy-preview-301--awesome-lamarr-6d076d.netlify.app/)
> Updates local elections for municipalities that had content last Nov

- _data/elections.yml
- _data/local_elections/local-2022-11.csv
- _includes/election-day.html
- _local-archive/local-2022-11.md
Updates election date to June.
> Updates election date

- _includes/local-election-data-no-details.html
- _local-archive/local-2023-06.md
- _pages/local.md
Attempts to get it to show November instead of June.
> Updates local elections page

- _data/elections.yml
- _includes/election-day.html
- _layouts/home.html
- _pages/local.md
Updates election dates on homepage and local elections page.
> Updated election dates

- _data/local_elections/local-2023-11.csv
Updated local election csv with fixed links.
Removed row for Bancroft, since it deorganized and doesn't have any contact info.
> Update csv file with fixed broken links

- _data/local_elections/local.csv
Fixes broken links on local elections page.
> Updates local election websites

- _layouts/home.html
Removes the coming soon content from the questions section on the homepage.
> Removes coming soon content

- _posts/2024-11-05-Q5_StateFlag.md
> Fixes typo in question 5

- _data/local_elections/67B4BE40
- _data/local_elections/local-2019-11.csv
- _data/local_elections/local-2020-07.csv
- _data/local_elections/local-2020-11.csv
- _data/local_elections/local-2021-06.csv
- _data/local_elections/local-2021-11.csv
- _data/local_elections/local-2022-06.csv
- _data/local_elections/local-2022-11.csv
- about.html
- local.csv
Ahrefs seems to actually be reporting 404s, which is cool. This PR fixes all the ones that are easily fixable.
(Should fix 10 of the 11)
> Fixes some 404s

- src/data/csv/local-elections/local-2022-06.csv
- src/data/csv/local-elections/local-2022-11.csv
- src/data/csv/local-elections/local-2023-06.csv
- src/data/csv/local-elections/local-2023-11.csv
- src/data/csv/local-elections/local.csv
Updates town of hartford links
> Hartford link update

- src/data/ballot-questions/november-2024/Q1_SuperPAC.mdx
- src/data/ballot-questions/november-2024/Q2_R&D-bond.mdx
- src/data/ballot-questions/november-2024/Q4_Trails.mdx
- src/data/ballot-questions/november-2024/Q5_StateFlag.mdx
Updates ballot measure results
> Ballot measure update

- src/data/ballot-questions/november-2023/Q1_QuasiBorrowing.mdx
- src/data/ballot-questions/november-2023/Q3_PineTreePower.mdx
Fixes the relative paths of a couple internal links
> Updates relative links

- src/components/global/google-analytics.astro
Fixes an issue with GA where parameters weren't being sent correctly
> Fix google analytics

- astro.config.ts
- package-lock.json
- package.json
Updates astro config to use cloudflare adapter so that we're able to use simpler redirects and handle them at the server level
Example redirect: https://cloudflare.maineballot.pages.dev/november%202024%20election/q1_superpac/
> Cloudflare

- package-lock.json
- src/components/react/mobile-menu.tsx
1. This is a bug fix. 
2. This is an enhancement or feature.
Updates or surpasses dependabot pull requests 398-399 and 412-414. Fixes breaking change in zag-js/menu for file mobile-menu.tsx in src/components/react folder.
> Updating astro dependencies
